### ISSUE TITLE
Public endpoint down

### ISSUE THREAD

**Issue by sten360** [elrumordelaluz/micro-svg-spreact#11]
Hi. 

This is probably not the best place to do this, but I didn't find any other way of contacting. It seems the public endpoint at https://micro-svg-spreact.now.sh/ is down and hence https://svgsprit.es/ is no longer working. I keep getting "An error was verified during your last svg processed" no matter what I try to upload. 

Hopyfully something can be done about this.
Thanks!

**Comment by elrumordelaluz** [comment]
Hi @sten360, thanks for open the _Issue_.

Seems a `now@1` issue I didn't handled before they cut down the _deployments_. Will fix it asap. 

Thanks for the input!

**Comment by fjoalland** [comment]
Is there a way to use it locally? If something happens again it could be a problem for me haha

**Comment by elrumordelaluz** [comment]
@fjoalland sure! you could always `clone` this _repository_ and run both the `endpoint` and the _App_ like:

```zsh
yarn start && cd app && yarn start
```

(remember to install all dependencies both in the root and in the `/app` directory)

**Comment by elrumordelaluz** [comment]
Solved. Will update the Readme with the new endpoint `url`.

**Comment by sten360** [comment]
Thank you so much for the fix!

**Comment by fjoalland** [comment]
Thank you!
